stages:
  - cs-fix
  - test

variables:
  PROJECT_NAME: hyperf
  REGISTRY_URL: registry-docker.org

run_test:
  stage: test
  before_script:
    - |
      cp .env.gitrunner .env
  script:
    - |
      git checkout ${CI_COMMIT_REF_NAME} --
      git pull origin ${CI_COMMIT_REF_NAME}
      rm -rf runtime/container/
      composer install
      php bin/hyperf.php migrate
      composer test
      echo 'done test case';
  only:
    - test
    - develop
    - tags
    - master
  tags:
    - test

cs-fix:
  stage: cs-fix
  before_script:
    - |
      echo "git checkout ${CI_COMMIT_REF_NAME} --";
      git checkout ${CI_COMMIT_REF_NAME} --
      git pull origin ${CI_COMMIT_REF_NAME}
      cp .env.gitrunner .env
  script:
    - |
      composer install
      composer cs-fix
      has_change_local=`git status | grep -E '(Changes to be committed|Changes not staged for commit|Untracked files)' || true`
      if [ ! -z "$has_change_local" ] && [ "${CI_COMMIT_REF_NAME}" = "master" ]; then
        git add .
        git commit -m 'auto code style fix'
        git pull
        git push origin master
      fi
      echo 'done cs-fix';
  only:
    - master
    - develop
    - test
  tags:
    - build
#cs-fix:
#  stage: cs-fix
#  before_script:
#      - |
#        cp .env.gitrunner .env
#  script:
#    - |
#      echo "git checkout ${CI_COMMIT_REF_NAME} --";
#      git checkout ${CI_COMMIT_REF_NAME} --
#      git pull origin ${CI_COMMIT_REF_NAME}
#      composer install
#      composer cs-fix
#      has_change_local=`git status | grep -E '(Changes to be committed|Changes not staged for commit|Untracked files)' || true`
#      if [ ! -z "$has_change_local" ] && [ "${CI_COMMIT_REF_NAME}" = "master" ]; then
#        git add .
#        git commit -m 'auto code style fix'
#        git pull
#        git push origin master
#      fi
#      echo 'done cs-fix';
#  only:
#    - master
#    - develop
#    - test
#  tags:
#    - build

